server:
  servlet:
    context-path: /api

spring:
  application:
    name: AuthSideApplication
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456 #Default Empty
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # Maximum number of connections, negative value means no limit, default is 8
          max-wait: -1    # Maximum blocking waiting time, negative value means no limit, default -1
          max-idle: 8     # Maximum idle connections, default 8
          min-idle: 0     # Minimum idle connection, default 0

    mongodb:
      uri: mongodb://127.0.0.1:27017/

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: 123456
